# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ecological Fractal Network
email: will.pearse@imperial.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  One of the greatest threats to the ecosystems we rely upon is not just a reduction in biodiversity, but also its homogenisation. The central goal of our network is to measure UK assemblage homogenisation and structure. We will achieve this by having network members establish sites, within which they will use fractal plot arrangements to efficiently measure diversity across spatial scales.
baseurl: ""
url: "https://ecofracnetwork.github.io/"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

